# Generated by Django 2.2 on 2019-04-23 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertodo',
            name='todo',
            field=models.IntegerField(),
        ),
    ]
